name: pull_request_check

on:
  pull_request:
    branches:
      - main
      - dev
      - hotfix/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: generate .env files
        run: echo -e ${{ secrets.SECRET_ENV }} > packages/apps/.env
      - name: install
        uses: docker://oichan/firebase-emulator-docker:latest
        with:
          args: npm ci
        env:
          CI: true
      - name: lint
        uses: docker://oichan/firebase-emulator-docker:latest
        with:
          args: npm run lint
        env:
          CI: true
      - name: build
        uses: docker://oichan/firebase-emulator-docker:latest
        with:
          args: npm run build
        env:
          CI: true
      - name: test
        uses: docker://oichan/firebase-emulator-docker:latest
        with:
          args: npm run test
        env:
          CI: true
